Repository alefragnani/vscode-copy-word, pull requests merged in 2022-03, with the labels that each got.

#39 Add Gitpod support
  .gitpod.yml
Labels: enhancement

#43 Features/support web
  .vscode/launch.json
  package-lock.json
  package.json
  tsconfig.json
  webpack.config.js
Labels: enhancement, internal

#41 Added support for paste.
  README.md
  package.json
  src/commands.ts
  src/constants.ts
Labels: enhancement, good first issue, PR needs update
